# Generated by Django 4.1.5 on 2023-04-03 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Creado')),
                ('modified', models.DateField(auto_now=True, verbose_name='Editado')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.trabajador')),
            ],
        ),
    ]
