# Generated by Django 4.1.5 on 2023-02-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reparaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reparacion',
            old_name='fecha',
            new_name='created',
        ),
        migrations.AddField(
            model_name='reparacion',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='sello_1',
            field=models.CharField(default='000000', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='reparacion',
            name='sello_2',
            field=models.CharField(default='000000', max_length=6, unique=True),
        ),
    ]
