# Generated by Django 4.2.5 on 2023-10-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salva', '0002_remove_area_pid_remove_computadora_pid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Area',
            new_name='SArea',
        ),
        migrations.RenameModel(
            old_name='Computadora',
            new_name='SComputadora',
        ),
        migrations.RenameModel(
            old_name='Diferencias',
            new_name='SDiferencias',
        ),
        migrations.RenameModel(
            old_name='Hardware',
            new_name='SHardware',
        ),
        migrations.RenameModel(
            old_name='Periferico',
            new_name='SPeriferico',
        ),
        migrations.RenameModel(
            old_name='Programs',
            new_name='SPrograms',
        ),
        migrations.RenameModel(
            old_name='Softwares',
            new_name='SSoftwares',
        ),
        migrations.RenameModel(
            old_name='Trabajador',
            new_name='STrabajador',
        ),
    ]
