# Generated by Django 4.2.5 on 2023-10-05 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salva', '0003_rename_area_sarea_rename_computadora_scomputadora_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdiferencias',
            name='computadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salva.scomputadora'),
        ),
    ]
