# Generated by Django 4.1.5 on 2023-08-02 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='ueb',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidades.ueb'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='area',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidades.area'),
        ),
    ]
