# Generated by Django 4.1.5 on 2023-04-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computadoras', '0002_alter_periferico_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computadora',
            name='baja',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='hardware',
            name='baja',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='periferico',
            name='baja',
            field=models.BooleanField(default=0),
        ),
    ]
