# Generated by Django 4.1.2 on 2023-04-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computadoras', '0003_computadora_baja_hardware_baja_periferico_baja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hardware',
            name='num_de_serie',
            field=models.CharField(blank=True, help_text='No. de serie', max_length=50, null=True),
        ),
    ]
