# Generated by Django 4.1.2 on 2023-04-04 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('computadoras', '0004_alter_hardware_num_de_serie'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hardware',
            unique_together=set(),
        ),
    ]
