# Generated by Django 4.1.5 on 2023-08-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computadoras', '0005_alter_hardware_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='diferencias',
            name='fecha',
            field=models.DateField(auto_now=True),
        ),
    ]
