# Generated by Django 4.2.5 on 2023-10-05 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('computadoras', '0006_diferencias_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computadora',
            name='nombre',
            field=models.CharField(help_text='Nombre de la computadora', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='computadora',
            name='num_de_inventario',
            field=models.CharField(blank=True, max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='diferencias',
            name='computadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='computadoras.computadora'),
        ),
    ]
