# Generated by Django 4.1.5 on 2023-02-23 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrinterStack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('toner', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrinterOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv', models.CharField(max_length=8, unique=True)),
                ('serial', models.CharField(max_length=8, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.trabajador')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printers.printerstack')),
            ],
        ),
    ]
