# Generated by Django 4.1.5 on 2023-02-23 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
        ('printers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printerowner',
            name='inv',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='printerowner',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidades.trabajador', verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='printerowner',
            name='printer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printers.printerstack', verbose_name='Impresora'),
        ),
        migrations.AlterField(
            model_name='printerowner',
            name='serial',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
